circleci orb found not working ... taking matters into my own hands

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,9 +1,162 @@
-orbs:
-  gcp-cli: circleci/gcp-cli@1.0.0
 version: 2.1
+
+commands:
+    initialize:
+        description: Initilize the gcloud CLI.
+        parameters:
+            gcloud-service-key:
+                default: GCLOUD_SERVICE_KEY
+                description: |
+                    Name of environment variable storing the full service key JSON file
+                    for the Google project.
+                type: env_var_name
+            google-compute-region:
+                default: GOOGLE_COMPUTE_REGION
+                description: The Google compute region to connect with via the gcloud CLI
+                type: env_var_name
+            google-compute-zone:
+                default: GOOGLE_COMPUTE_ZONE
+                description: The Google compute zone to connect with via the gcloud CLI.
+                type: env_var_name
+            google-project-id:
+                default: GOOGLE_PROJECT_ID
+                description: The Google project ID to connect with via the gcloud CLI.
+                type: env_var_name
+        steps:
+            - orb-tools/check-env-var-param:
+                command-name: Checking whether required env vars are set to initialize gcloud CLI...
+                param: <<parameters.gcloud-service-key>>,<<parameters.google-project-id>>
+            - run:
+                command: |
+                    # Store service account
+                    echo $<<parameters.gcloud-service-key>> > ${HOME}/gcloud-service-key.json
+
+                    # Initialize gcloud CLI
+                    gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
+                    gcloud --quiet config set project $<<parameters.google-project-id>>
+
+                    if [[ -n $<<parameters.google-compute-zone>> ]]; then
+                      gcloud --quiet config set compute/zone $<<parameters.google-compute-zone>>
+                    elif [[ -n $<<parameters.google-compute-region>> ]]; then
+                      gcloud --quiet config set compute/region $<<parameters.google-compute-region>>
+                    else
+                      echo "ERROR: Set <<parameters.google-compute-zone>> or <<parameters.google-compute-region>> env variable" >&2
+                      exit 1
+                    fi
+                name: Initialize gcloud CLI to connect to Google Cloud
+    install:
+        description: |
+            Install the gcloud CLI. When installing within the Docker executor, the
+            install will only occur if the CLI isn't already installed. If installing in
+            a Linux machine image, it will remove the pre-installed version and instead
+            install the version specified by this orb.
+        parameters:
+            version:
+                default: 283.0.0
+                description: 'Version of the CLI to install. Must contain the full version number as it appears in the URL on this page: https://cloud.google.com/sdk/docs/downloads-versioned-archives'
+                type: string
+        steps:
+            - run:
+                command: |
+                    install () {
+                      # Set sudo to work whether logged in as root user or non-root user
+                      if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
+                      cd ~/
+                      curl -Ss --retry 5 https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-<<parameters.version>>-linux-x86_64.tar.gz | tar xz
+                      echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
+                    }
+
+                    if grep 'docker\|lxc' /proc/1/cgroup > /dev/null 2>&1; then
+                      if [[ $(command -v gcloud) == "" ]]; then
+                        install
+                      else
+                        echo "gcloud CLI is already installed."
+                      fi
+                    else
+                      echo "----------------------------------------------------------------------------------------------------"
+                      echo "this is a machine executor job, replacing default installation of gcloud CLI"
+                      echo "----------------------------------------------------------------------------------------------------"
+                      sudo rm -rf /opt/google-cloud-sdk
+                      install
+                    fi
+                name: Install latest gcloud CLI version, if not available
+            - run:
+                command: gcloud version
+                name: gcloud CLI version
+
 workflows:
-  install_and_configure_cli:
-    jobs:
-      - gcp-cli/install_and_initialize_cli:
-          context: gcp-bucket-build
-          executor: gcp-cli/default
+    install_and_configure_cli:
+        jobs:
+            - install_and_initialize_cli:
+                context: myContext
+                executor: gcp-cli/default
+
+executors:
+    default:
+        description: The default executor is the CircleCI Python Convenience Image.
+        docker:
+            - image: cimg/python:<<parameters.version>>
+        parameters:
+            version:
+                default: "3.7"
+                description: |
+                    Python version to use. Take into account the versions of Python available
+                    from CircleCI (https://hub.docker.com/r/cimg/python/tags) as well as what
+                    is supported by gcloud CLI itself (https://cloud.google.com/sdk/docs/install).
+                type: string
+    google:
+        description: The official Google Docker image with gcloud SDK and CLI pre-installed.
+        docker:
+            - image: google/cloud-sdk:<<parameters.sdk-version>>
+        parameters:
+            sdk-version:
+                default: latest
+                description: |
+                    What version of the Google Cloud SDK Docker image? For full options, see https://hub.docker.com/r/google/cloud-sdk/tags
+                type: string
+    machine:
+        description: |
+            CircleCI's machine executor:
+            https://circleci.com/docs/2.0/executor-types/#using-machine
+        machine:
+            image: <<parameters.image>>
+        parameters:
+            image:
+                default: ubuntu-2004:202010-01
+                description: |
+                    Which machine executor image to use. For details, see
+                    https://circleci.com/docs/2.0/configuration-reference/#machine
+                type: string
+jobs:
+    install_and_initialize_cli:
+        description: Install gcloud CLI and initialize to connect to Google Cloud.
+        executor: <<parameters.executor>>
+        parameters:
+            executor:
+                default: default
+                description: |
+                    Executor to use for this job. Defaults to this orb's default executor.
+                type: executor
+            gcloud-service-key:
+                default: GCLOUD_SERVICE_KEY
+                description: The gcloud service key
+                type: env_var_name
+            google-compute-region:
+                default: GOOGLE_COMPUTE_REGION
+                description: The Google compute region to connect with via the gcloud CLI
+                type: env_var_name
+            google-compute-zone:
+                default: GOOGLE_COMPUTE_ZONE
+                description: The Google compute zone to connect with via the gcloud CLI
+                type: env_var_name
+            google-project-id:
+                default: GOOGLE_PROJECT_ID
+                description: The Google project ID to connect with via the gcloud CLI
+                type: env_var_name
+        steps:
+            - install
+            - initialize:
+                gcloud-service-key: <<parameters.gcloud-service-key>>
+                google-compute-region: <<parameters.google-compute-region>>
+                google-compute-zone: <<parameters.google-compute-zone>>
+                google-project-id: <<parameters.google-project-id>>
